### ISSUE TITLE
Please add a way for a template description

### ISSUE THREAD

**Issue by mmynsted** [commercialhaskell/stack-templates#50] opened 2016-03-25 20:57 UTC
Please add a way to provide a template description.  Perhaps something like `mytemplatename.hsfiles.md` to go with the `mytemplatename.hsfiles` file?

**Comment by mgsloan** [comment] 2016-03-28 18:41
Yes, it's a good idea - dupe of https://github.com/commercialhaskell/stack/issues/1571

Feel free to work on implementing this!  It may be quite a while for us stack maintainers to get around to implementing some of the lower priority enhancements like this

**Closed by mgsloan** 2016-03-28 18:42 UTC
